#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_3x3(MO(1), KC_VOLD, KC_VOLU, KC_LALT, KC_UP, KC_ENT, KC_LEFT, KC_DOWN, KC_RGHT),
	[1] = LAYOUT_ortho_3x3(RGB_TOG, RGB_RMOD, RGB_MOD, RGB_M_R, RGB_M_SW, RGB_M_SN, RGB_M_X, RGB_M_G, RESET)
};
